version: '3.8'

services:
  db:
    image: postgres:16-alpine
    # platform: linux/arm64  # Commented for GitHub Actions compatibility
    environment:
      POSTGRES_DB: ${DATABASE:-quizzes}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:7-alpine
    # platform: linux/arm64  # Commented for GitHub Actions compatibility
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  web:
    build: 
      context: .
      # platforms:
      #   - linux/arm64  # Commented for GitHub Actions compatibility
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    volumes:
      - bundle_cache:/usr/local/bundle
      - ./log:/rails/log
      - ./tmp:/rails/tmp
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE=${DATABASE:-quizzes}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    # platform: linux/arm64  # Commented for GitHub Actions compatibility
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/var/www/public:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  test:
    build: 
      context: .
    command: |
      sh -c "
        echo 'Waiting for services to be ready...' &&
        until curl -f http://web:3000/health 2>/dev/null; do sleep 2; done &&
        until curl -f http://nginx:80/health 2>/dev/null; do sleep 2; done &&
        echo 'All services are ready!' &&
        curl -f http://nginx:80/health &&
        curl -f -I http://nginx:80/ &&
        echo 'Production test completed successfully!'
      "
    depends_on:
      web:
        condition: service_healthy
      nginx:
        condition: service_started
    environment:
      - RAILS_ENV=production

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
