default: &default
  adapter: mysql2
  database: <%= ENV['DATABASE'] || 'quizzes' %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  username: <%= ENV['MYSQL_USER'] || 'jiri' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'heslo' %>
  encoding: utf8mb4


development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE'] || 'quizzes_test' %>

production:
  <<: *default
