default: &default
  adapter: postgresql
  database: <%= ENV['DATABASE'] || 'quizzes' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  encoding: unicode


development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE'] || 'quizzes_test' %>

production:
  <<: *default
