name: CI

on:
  push:

jobs:
  rubocop:
    needs: setup
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop ./app

  rspec:
    needs: setup
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: quizzes_test
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      RAILS_ENV: test
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      DATABASE: quizzes_test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7
          bundler-cache: true

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot --silent && break
            sleep 1
          done

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Setup test database
        run: bin/rails db:create db:schema:load

      - name: Run RSpec
        run: bundle exec rspec
